apiVersion: apps/v1
kind: Deployment
metadata:
  name: bamghoug-iot-p3
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: iot-p3
        image: bamghoug/iot-p3:v1
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: iot-p3-svc
spec:
  selector:
    app.kubernetes.io/name: bamghoug-iot-p3
  ports:
    - protocol: TCP
      port: 80
